[package]
name = "dispatch-play"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13.5"
prost-types = "0.13.5"
rdkafka = "0.37.0"
tokio = { version = "1.45.0", features = ["full"] }
uuid = { version = "1.16.0", features = ["v4"] }

[build-dependencies]
prost-build = "0.13.5"
